download.file(url = 'https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip', destfile = 'household_power_consumption.zip')
unzip('household_power_consumption.zip')
data = read.csv(file = 'household_power_consumption.txt', header = TRUE, sep = ';')
data$Date = as.Date(data$Date, format = '%d/%m/%Y')
data_subset <- subset(data, data$Date >= "2007-02-01" & data$Date < "2007-02-03")
data_subset$Global_active_power <- as.numeric(as.character(data_subset$Global_active_power))
png(file = "plot1.png", width = 480, height = 480)
hist(data_subset$Global_active_power, main = 'Global Active Power', xlab = 'Global Active Power (kilowatts)', col = 'red')
dev.off()
